version: "3"

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            TZ: ${WORKSPACE_TIMEZONE}
        volumes:
            - ./MariaDB/data:/var/lib/mysql
            - ./MariaDB/conf.d:/etc/mysql/conf.d
        ports:
            - "${MARIADB_PORT}:3306"
        networks:
            - default
            
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test_db
            TZ: ${WORKSPACE_TIMEZONE}
        ports:
            - "${POSTGRES_PORT}:5432"
        networks:
            - default
            
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mariadb
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        ports:
            - "${PMA_PORT}:80"
        networks:
            - default
            
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
            TZ: ${WORKSPACE_TIMEZONE}
        ports:
            - "${PGA_PORT}:80"
        networks:
            - default

networks:
  default:
    external: false
    name: backend-network
